"""
Security Event Alerting — CIPHRA
Monitors audit log events and triggers alerts for suspicious activity.

Covers:
  - Brute-force / repeated login failures
  - Account lockouts
  - Privilege escalation attempts
  - High-volume API requests from a single IP
  - Suspicious user-agent patterns
"""

import logging
import smtplib
import ssl
from collections import defaultdict, deque
from datetime import datetime, timedelta, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from app.config import settings

logger = logging.getLogger("ciphra.alerting")


# ─── Thresholds ───────────────────────────────────────────────────────────────

LOGIN_FAIL_THRESHOLD = 10        # alert after this many failures across all IPs
LOCKOUT_ALERT_THRESHOLD = 3      # alert after this many lockouts in the window
ALERT_WINDOW_MINUTES = 10        # sliding window for threshold checks
HIGH_VOLUME_REQUESTS = 100       # requests from a single IP in the window


# ─── In-memory sliding window counters ────────────────────────────────────────
# For production, replace with Redis for multi-process safety.

_login_failures: deque = deque()          # timestamps of global login failures
_lockout_events: deque = deque()          # timestamps of lockout events
_ip_requests: defaultdict = defaultdict(deque)  # IP -> deque of timestamps
_alerted: dict = {}                       # event_key -> last alerted datetime


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _now() -> datetime:
    return datetime.now(timezone.utc)


def _purge_old(dq: deque, window_minutes: int) -> None:
    """Remove entries older than the sliding window."""
    cutoff = _now() - timedelta(minutes=window_minutes)
    while dq and dq[0] < cutoff:
        dq.popleft()


def _should_alert(key: str, cooldown_minutes: int = 15) -> bool:
    """Prevent alert spam — only alert once per cooldown window per key."""
    last = _alerted.get(key)
    if last is None or (_now() - last).total_seconds() > cooldown_minutes * 60:
        _alerted[key] = _now()
        return True
    return False


# ─── Alert Dispatcher ─────────────────────────────────────────────────────────

def _dispatch_alert(level: str, title: str, body: str, metadata: Optional[dict] = None) -> None:
    """
    Central alert dispatcher. Logs always. Sends email if configured.
    Extend this to send to Slack, PagerDuty, SIEM, etc.
    """
    meta_str = ""
    if metadata:
        meta_str = " | ".join(f"{k}={v}" for k, v in metadata.items())

    log_msg = f"[SECURITY ALERT] [{level}] {title} | {meta_str}"

    if level == "CRITICAL":
        logger.critical(log_msg)
    elif level == "HIGH":
        logger.error(log_msg)
    else:
        logger.warning(log_msg)

    # Email alert if SMTP is configured in settings
    if getattr(settings, "ALERT_EMAIL_ENABLED", False):
        _send_email_alert(level, title, body, metadata)


def _send_email_alert(
    level: str,
    title: str,
    body: str,
    metadata: Optional[dict] = None,
) -> None:
    """Send an email alert via SMTP. Configure in .env."""
    try:
        smtp_host = getattr(settings, "ALERT_SMTP_HOST", "")
        smtp_port = getattr(settings, "ALERT_SMTP_PORT", 587)
        smtp_user = getattr(settings, "ALERT_SMTP_USER", "")
        smtp_pass = getattr(settings, "ALERT_SMTP_PASS", "")
        alert_from = getattr(settings, "ALERT_FROM_EMAIL", smtp_user)
        alert_to = getattr(settings, "ALERT_TO_EMAIL", "")

        if not all([smtp_host, smtp_user, smtp_pass, alert_to]):
            logger.debug("Email alerting not fully configured — skipping.")
            return

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[CIPHRA {level}] {title}"
        msg["From"] = alert_from
        msg["To"] = alert_to

        meta_rows = ""
        if metadata:
            meta_rows = "".join(
                f"<tr><td><b>{k}</b></td><td>{v}</td></tr>"
                for k, v in metadata.items()
            )

        html = f"""
        <html><body>
        <h2 style='color:{"red" if level == "CRITICAL" else "orange"}'>
            [{level}] {title}
        </h2>
        <p>{body}</p>
        <table border='1' cellpadding='6'>{meta_rows}</table>
        <p><small>Generated by CIPHRA Security Alerting — {_now().isoformat()}</small></p>
        </body></html>
        """

        msg.attach(MIMEText(html, "html"))

        context = ssl.create_default_context()
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls(context=context)
            server.login(smtp_user, smtp_pass)
            server.sendmail(alert_from, alert_to, msg.as_string())

        logger.info("Alert email sent to %s", alert_to)

    except Exception as e:
        logger.error("Failed to send alert email: %s", e)


# ─── Event Handlers ───────────────────────────────────────────────────────────

def on_login_failure(username: str, ip_address: str) -> None:
    """
    Track login failures. Alert if threshold exceeded in the sliding window.
    """
    now = _now()
    _login_failures.append(now)
    _purge_old(_login_failures, ALERT_WINDOW_MINUTES)

    if len(_login_failures) >= LOGIN_FAIL_THRESHOLD:
        if _should_alert("login_failures"):
            _dispatch_alert(
                level="HIGH",
                title=f"Brute-force detected: {len(_login_failures)} login failures in {ALERT_WINDOW_MINUTES}m",
                body=(
                    f"Multiple login failures detected in a short window. "
                    f"This may indicate a brute-force or credential stuffing attack."
                ),
                metadata={
                    "trigger_username": username,
                    "trigger_ip": ip_address,
                    "failure_count": len(_login_failures),
                    "window_minutes": ALERT_WINDOW_MINUTES,
                    "time": now.isoformat(),
                },
            )


def on_account_lockout(username: str, ip_address: str) -> None:
    """
    Alert when accounts are being locked out repeatedly.
    """
    now = _now()
    _lockout_events.append(now)
    _purge_old(_lockout_events, ALERT_WINDOW_MINUTES)

    if len(_lockout_events) >= LOCKOUT_ALERT_THRESHOLD:
        if _should_alert("account_lockouts"):
            _dispatch_alert(
                level="HIGH",
                title=f"Multiple account lockouts: {len(_lockout_events)} in {ALERT_WINDOW_MINUTES}m",
                body=(
                    f"Several accounts have been locked out in a short time window. "
                    f"Possible coordinated brute-force attack."
                ),
                metadata={
                    "locked_username": username,
                    "trigger_ip": ip_address,
                    "lockout_count": len(_lockout_events),
                    "time": now.isoformat(),
                },
            )


def on_privilege_escalation(username: str, attempted_role: str, ip_address: str) -> None:
    """
    Alert immediately on any privilege escalation attempt — always CRITICAL.
    """
    if _should_alert(f"privesc_{username}", cooldown_minutes=5):
        _dispatch_alert(
            level="CRITICAL",
            title=f"Privilege escalation attempt by '{username}'",
            body=(
                f"User '{username}' attempted to access a role or resource "
                f"they are not authorised for."
            ),
            metadata={
                "username": username,
                "attempted_role": attempted_role,
                "ip_address": ip_address,
                "time": _now().isoformat(),
            },
        )


def on_high_volume_requests(ip_address: str) -> None:
    """
    Track per-IP request volume. Alert if a single IP exceeds the threshold.
    """
    now = _now()
    dq = _ip_requests[ip_address]
    dq.append(now)
    _purge_old(dq, ALERT_WINDOW_MINUTES)

    if len(dq) >= HIGH_VOLUME_REQUESTS:
        if _should_alert(f"high_volume_{ip_address}"):
            _dispatch_alert(
                level="HIGH",
                title=f"High request volume from IP {ip_address}",
                body=(
                    f"IP {ip_address} has sent {len(dq)} requests "
                    f"in the last {ALERT_WINDOW_MINUTES} minutes. Possible DDoS."
                ),
                metadata={
                    "ip_address": ip_address,
                    "request_count": len(dq),
                    "window_minutes": ALERT_WINDOW_MINUTES,
                    "time": now.isoformat(),
                },
            )


def on_suspicious_user_agent(ip_address: str, user_agent: str) -> None:
    """
    Alert when known scanner or attack tool user agents are detected.
    """
    SUSPICIOUS_AGENTS = [
        "nikto", "sqlmap", "nmap", "masscan", "zgrab",
        "nuclei", "dirbuster", "hydra", "metasploit", "burpsuite",
    ]
    ua_lower = user_agent.lower()
    matched = next((a for a in SUSPICIOUS_AGENTS if a in ua_lower), None)

    if matched and _should_alert(f"ua_{ip_address}_{matched}"):
        _dispatch_alert(
            level="HIGH",
            title=f"Suspicious user agent detected from {ip_address}",
            body=f"A known attack tool signature '{matched}' was detected in the User-Agent header.",
            metadata={
                "ip_address": ip_address,
                "user_agent": user_agent,
                "matched_signature": matched,
                "time": _now().isoformat(),
            },
        )